name: Terraform destroy

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Environment type [test]'
        required: true
        options:
          - test
      confirm:
        type: boolean
        description: 'Confirm that you want to destroy the environment'
        required: true

jobs:
  tfm-destroy:
    name: tfm-destroy
    if: ${{ github.event.inputs.confirm == true }} # Runs only if confirmed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials for AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5

      - name: Terraform Init & Destroy
        run: |
          echo "Cleaning up .terraform folder"
          rm -rf .terraform
          echo "Running terraform init"
          terraform init
          echo "Running terraform destroy"
          terraform destroy -auto-approve --var-file="./variables/variables.tfvars"
        working-directory: ./terraform/
